### ISSUE TITLE
Up button wont work

### ISSUE THREAD

**Issue by bigredno38** [10yard/dkafe#1]
For some reason the up arrow key will no longer work ,I have tried different keys and still nothing
any suggestions

Thanks

**Comment by 10yard** [comment]
Hi, thats's odd, if it's just up arrow.  Can you let me know version and what OS you're running and I'll take a look.  Jon

**Comment by bigredno38** [comment]
I know...it was working fine.....Im working on finishing the 3rd row of
games and it just started out of nowhere....
and also when I hit the tab key in game...sometimes it'll start moving on
its own...which btw I can use the up arrow in the mame menu

I have the .36 version of DKAFE

Edition Windows 10 Pro
Version 21H1
Installed on ‎3/‎9/‎2021
OS build 19043.2006
Experience Windows Feature Experience Pack 120.2212.4180.0

Processor Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz   3.70 GHz
Installed RAM 16.0 GB
System type 64-bit operating system, x64-based processor

Steve

**Comment by 10yard** [comment]
Thanks for the info Steve

Couple of things to try before retesting.

1) Add the following line to the settings.txt file.
`USE_JOYSTICK = 0`

2) Unplug or disable your mouse input temporarily.

I'm unable to replicate your issue but suspect there to be some rogue input coming from somewhere.

**Comment by 10yard** [comment]
Further to above.  Also check you have default controls set correctly in the settings.txt file.  i.e.

```
CONTROL_LEFT = left
CONTROL_RIGHT = right
CONTROL_UP = up
CONTROL_DOWN = down
CONTROL_JUMP = left ctrl
CONTROL_ACTION = left alt
CONTROL_P1 = 1
CONTROL_P2 = 2
CONTROL_COIN = 5
CONTROL_EXIT = escape
CONTROL_SETTINGS = tab
```

**Comment by bigredno38** [comment]
Ok thanks....I will do both thanks after work today and let you knowSteveSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Jon Wilson ***@***.***> Date: 10/7/22  5:26 AM  (GMT-05:00) To: 10yard/dkafe ***@***.***> Cc: bigredno38 ***@***.***>, Author ***@***.***> Subject: Re: [10yard/dkafe] Up button wont work (Issue #1) 
Thanks for the info Steve
Couple of things to try before retesting.


Add the following line to the settings.txt file.
USE_JOYSTICK = 0


Unplug or disable your mouse input temporarily.


I'm unable to replicate your issue but suspect there to be some rogue input coming from somewhere.

**Comment by bigredno38** [comment]
OK   did the joystick to 0 and so far everything is good thanks...but 2
other questions.....The hiscores arent saving and how to I added your
latest rom hacks Allen Kong,2NUTKong,Noluck Kong OctoMonkey, Half Kong and
Quarter Kong

Thanks again for the keyboard help

Steve

**Comment by 10yard** [comment]
Glad to hear keyboard issue is fixed for you.  High scores don't automatically save,  maybe that's something I can introduce.  My 6 new rom hacks are included in the next release v0.37.  I'll be releasing that when back from holiday in about 8 days.  If you can't wait until then they're available in a multikong package I have on discord channel.  If you're on discord send me your user name and I,ll drop youan invite.  Jon

**Comment by bigredno38** [comment]
OK..on the highscores.....Ill wait until the .37 release,I still have to
unlock more DK games so that will keep me busy...
and Id like to join the discord channel my username is Steve Staser #3366

Thanks

**Comment by 10yard** [comment]
Hi Steve,  I've made v0.37 release available for Windows.  It includes all the new rom hack stuff and the fix for that Joystick issue you reported.  Closing this issue off now.  Cheers Jon

**Comment by bigredno38** [comment]
Awesome,can't to try out the new stuff,and thanks again for your helpSteveSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Jon Wilson ***@***.***> Date: 10/14/22  12:41 PM  (GMT-05:00) To: 10yard/dkafe ***@***.***> Cc: bigredno38 ***@***.***>, Author ***@***.***> Subject: Re: [10yard/dkafe] Up button wont work (Issue #1) 
Hi Steve,  I've made v0.37 release available for Windows.  It includes all the new rom hack stuff and the fix for that Joystick issue you reported.  Closing this issue off now.  Cheers Jon
