### ISSUE TITLE
Donkey Kong Reverse uses incorrect game title on game description

### ISSUE THREAD

**Issue by Superjustinbros** [10yard/dkafe#11]
![image](https://github.com/10yard/dkafe/assets/4167951/5bff8093-c699-415f-b4fc-6b5e3f367c1a)
If you approach the machine for Donkey Kong Reverse, the text box that pops up mistakenly says "Donkey Kong Springfinity" instead of the correct title.

**Comment by 10yard** [comment]
Issue is resolved and pushed to git.  Thank you.
The next release will be out very soon :)
