### ISSUE TITLE
How to rotate the frontend?

### ISSUE THREAD

**Issue by ncflagg** [10yard/dkafe#12]
I can use the -ror command argument to rotate the dkwolf emulator, but how do I rotate the frontend? I'm using the XP version.

**Comment by 10yard** [comment]
An option to rotate the frontend (90, 180, 270) should be provided in the next release.

**Comment by 10yard** [comment]
Good news
A ROTATION setting is added to the settings file in the next release.  

Bad news
It was not possible to implement the rotation in Windows XP after much effort.  I'm using a backported version of Python for XP and the Win32 libraries are not playing ball.  If a better backported Python version ever appears then I will definitely take another look at this.  Sorry.
It will work on anything up from Windows Vista.

**Comment by ncflagg** [comment]
Ok. Thanks for your effort.
Rotating the Windows XP Desktop 90 degrees seems to be hit and miss. With my ATI card and XP SP3 at 640x480, I can't get it to work. I'll try it on a future arcade cabinet build with Windows 7.
