### ISSUE TITLE
v0.63 Fatal Crash after installing Addon Pack

### ISSUE THREAD

**Issue by Superjustinbros** [10yard/dkafe#15]
After installing the latest version of the addon pack in Version 0.63, this window pops up and all further attempts to frontend the game are also bricked by the same message:
![image](https://github.com/10yard/dkafe/assets/4167951/f435eec9-a09e-42c2-85a5-fe1db206476a)

**Comment by 10yard** [comment]
Thanks Justin.  It's a stupid bug introduced in v0.63. I hope to get an update out on Sunday when I'm back home from a break.  Also,  I'll look at a method of catching trivial bugs so they don't brick the frontend in future.
