### ISSUE TITLE
Illegal multibyte sequence (instant crash on startup)

### ISSUE THREAD

**Issue by nerdgh0st** [10yard/dkafe#16]
![launch_L9guM43Myc](https://github.com/user-attachments/assets/0d514b47-4750-4a68-870b-cf983ef8cdb4)

The app will start when "dkong.zip" is put into the roms folder. Upon pressing jump, it brings this error up, and will not launch whatsoever after that. It will crash as soon as the app opens

**Comment by 10yard** [comment]
Thanks for reporting this error.
There was an illegal/unrecognised character in one of the game text files - that contain the game description.   I have added logic to detect and ignore, and have also updated the effected game text file.

I made an update to the latest release which is available to download.  Hopefully all good now.
