### ISSUE TITLE
[Suggestion] High Score Saving

### ISSUE THREAD

**Issue by Superjustinbros** [10yard/dkafe#4]
Since MAME supports high score saving through an optional plugin and because it's present in most modern arcade compilations in some way or another, I was wondering if that feature could be carried over into DKAFE's WolfMAME and configured to work with most, if not all, of the games in the arcade.

**Comment by 10yard** [comment]
Yes,  high score saving is certainly doable.  I will test and hope to add support into the next release.  Thank you.

**Comment by 10yard** [comment]
High score saving was added and changes were committed to the master branch.
A `HIGH_SCORE_SAVE` setting was added to the settings.txt file and an option was added to the frontend menu.
High scores are retained separately for all of the hacks which share the same parent rom - dkong.zip. 

Release 0.41 will include this change.
