### ISSUE TITLE
Jumpman stuck at machines after winning prize

### ISSUE THREAD

**Issue by Superjustinbros** [10yard/dkafe#5]
In a few cases, when returning to the DKAFE frontend after closing out of a game with a score high enough to win a prize, Jumpman does not immediately respond to any directional inputs, leaving him temporally immobilized as prize money is sent out.

**Comment by Superjustinbros** [comment]
I should add that this may be because when exiting a game and returning to a frontend, the frontend is not always put into focus, instead bringing one of the other windows/programs on my desktop to the front instead.

**Comment by 10yard** [comment]
Your extra info is helpful.  I will see if I can force focus back to DKAFE frontend on exit of MAME - in the case it doesn't automatically grab it.

**Comment by Superjustinbros** [comment]
After some further testing, this issue may be specifically for windowed mode- I tested with fullscreen and I was able to move Jumpman immediately upon returning to the frontend.

**Comment by 10yard** [comment]
I made a plugin to grab focus back to the frontend after exiting a game.  It's Windows OS only for now.
There is a new setting called REFOCUS_WINDOW in settings.txt (under the DKWolf/Interface settings section:
If defaults to 0.  

If you set this to 1 then it will attempt to refocus back to DKAFE on exit of game.

REFOCUS_WINDOW = 1

I will be pushing out a new release of DKAFE soon.

**Comment by 10yard** [comment]
Tested and working on Windows in latest v0.41 release.
