### ISSUE TITLE
Intro Sequence Oddity

### ISSUE THREAD

**Issue by Superjustinbros** [10yard/dkafe#6]
![image](https://github.com/10yard/dkafe/assets/4167951/de276571-9b3b-48bf-823e-3581c9bf914a)
During the intro sequence that plays after the title screen, if there is any machine set to appear in Slot 02, Pauline's speech bubbles for that machine will appear before the intro ends and Jumpman spawns in the level.

Here, I've added the Japanese Donkey Kong machine into Slot 02 for demonstration purposes.

In addition, the design of the "L=01" on the top right corner is inconsistent between the intro and the menu once you gain control of Jumpman.

**Comment by 10yard** [comment]
Well spotted!  
It was a simple fix to suppress Pauline's speech bubbles when the intro sequence is playing.  
The "L=01" was 1 pixel too far over to the right in the frontend (obvious after the intro completes).
These fixes will be included in the next DKAFE release.  
Thank you.
