### ISSUE TITLE
DK Wizardry Text Color Error

### ISSUE THREAD

**Issue by Superjustinbros** [10yard/dkafe#7]
In DK Wizardry, if you score 10,000 points and win a prize, the text that otherwise replaces the high score text is not all colored blue.
![0000](https://github.com/10yard/dkafe/assets/4167951/9bb5fe46-a232-41d6-a14c-80be0e7aba41)

**Comment by 10yard** [comment]
This is resolved in my latest commit.  The DK Wizardry rom (by Paul Goes) uses a custom palette.  The blue area on the top line is reserved for the 8 character "WIZARDRY" text.  I workaround this restriction by limiting the size of the prize award message displayed by DKAFE to 8 characters.
e.g.
WON 3RD!
WON 2ND!
WON 1ST!

Note: That Wizardry rom makes use of the P2 button (to cast spells displayed top-right) so the HUD is switched off.
